name: Evan Walsh
url: http://evanwalsh.net
markdown: kramdown
highlighter: rouge
destination: public
exclude:
  - Rakefile
  - README.md
  - public
  - Gemfile
  - Gemfile.lock
  - config
  - bin
paginate: 20
paginate_path: pages/:num
permalink: :year/:month/:title
sass:
  syntax: sass
  style:  compressed
  sass_dir: ./assets/stylesheets/
announcement:
  enabled: false
  text: This is a test &rarr;
  link: http://evanwalsh.net
defaults:
  - scope:
      path: ''
      type: post
    values:
      layout: post
  - scope:
      path: ''
      type: page
    values:
      layout: page
