#!/usr/bin/env ruby

require "fileutils"
require "rubygems"
require "bundler/setup"
Bundler.require(:default)

class Blog < Thor
  include FileUtils

  COLORS = {
    green: "#5cb635"
  }

  desc "draft NAME", "Draft a post"
  method_options :format => :optional
  def draft name
    format = options[:format] || "md"
    slug = name.downcase.gsub(/ +/,'-').gsub(/[^-\w]/,'').sub(/-+$/,'')
    filename = slug + ".#{format}"
    mkdir_p "_drafts"

    if File.exists?("_drafts/#{filename}")
      puts "#{filename} already exists!"
      return
    end

    File.open("_drafts/#{filename}","w+") do |f|
      f.puts "---"
      f.puts "layout: post"
      f.puts "title: #{name}"
      f.puts "categories: []"
      f.puts "tags: []"
      f.puts "external: false"
      f.puts "---"
    end
    puts "Created _drafts/#{filename}".color(COLORS[:green])
  end

  desc "publish [FILE]", "Publish a post"
  def publish file = nil
    unless file
      puts "Choose file:"
      @files = Dir["_drafts/*"]
      @files.each_with_index { |f,i| puts "#{i+1}: #{f}" }
      print "> "
      num = STDIN.gets
      file = @files[num.to_i - 1]
    end

    now = Date.today.strftime("%Y-%m-%d")
    mv file, "_posts/#{now}-#{File.basename(file)}"

    puts "Published post: #{now}-#{File.basename(file)}".color(COLORS[:green])
  end
end

Blog.start(ARGV)
